apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: oss-check-test
  description: OSS Vulnerability Check API with path parameters
  tags:
    - security
    - oss
spec:
  type: openapi
  lifecycle: experimental
  owner: team-security
  definition: |
    openapi: 3.0.0
    info:
      title: OSS Check API
      version: 1.0.0
      description: API for checking OSS vulnerabilities using path parameters
    servers:
      - url: https://16.103.37.82
        description: Local OSS Check service
    paths:
      /oss-check-ui/{package_type}/{package_name}/{version}:
        post:
          summary: Check OSS vulnerability
          operationId: checkOssPathParams
          parameters:
            - name: package_type
              in: path
              required: true
              schema:
                type: string
              description: Package type (e.g., maven, npm)
            - name: package_name
              in: path
              required: true
              schema:
                type: string
              description: Name of the package
            - name: version
              in: path
              required: true
              schema:
                type: string
              description: Version of the package
          responses:
            '200':
              description: Successful check
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        example: success
                      total_vulnerabilities:
                        type: integer
                      is_safe:
                        type: boolean
            default:
              description: Error response
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      error:
                        type: string
